# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'texchange' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod ‘Firebase/Core’
  pod ‘Firebase/Database’

  # Pods for texchange

  target 'texchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'texchangeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
